blank_issues_enabled: false
contact_links:
  - name: Suporte
    url: https://github.com/orgs/PlataformaGalleriaMellonella/discussions
    about: Se vocÃª precisar de suporte, visite nossa pÃ¡gina de discussÃµes.
issue_templates:
  - name: ğŸ› Reportar Bug
    description: Use este template para relatar um bug.
    labels: [bug]
    title: ""
    body: .github/ISSUE_TEMPLATE/bug_report.md
  - name: ğŸš€ Solicitar Funcionalidade
    description: Use este template para sugerir uma nova funcionalidade.
    labels: [enhancement]
    title: ""
    body: .github/ISSUE_TEMPLATE/feature_request.md
